v1.0.5
logzio/kubernetes-instrumentor pull request #9
Opened 2023-07-03 08:55 UTC by yotamloe

* v1.0.5
    - remove `JAVA_OPTS` `JAVA_TOOL_OPTIONS` `NODE_OPTIONS` if they are empty

2023-07-03 09:54 UTC, mirii1994 approved these changes

2023-07-18 06:57 UTC, mirii1994 requested changes
Awesome job, please see my comments :)

2023-07-18 06:57 UTC, mirii1994 commented on instrumentor/controllers/common.go
> +		updateErr := c.Update(ctx, object)
Why new `updateErr` and not just use existing err?

2023-07-18 06:57 UTC, mirii1994 commented on instrumentor/controllers/common.go
> -		backoff := wait.Backoff{
Out of curiosity - why are we removing the retry?

2023-07-18 06:57 UTC, mirii1994 commented on instrumentor/controllers/common.go
> +			logger.Error(err, "error updating active service name for deployment / statefulset")
It'll not be fun to remember updating this line whenever we'll support a new resource. Please change it to a generic term 🙏

2023-07-18 08:25 UTC, yotamloe commented on instrumentor/controllers/common.go
> -		backoff := wait.Backoff{
The current retry logic was wrong since it didn't use `get` at the beginning and that causes the retry to always fail. besides that the operator tries to reach a certain state-based to annotations so even if a single request fails the operator will try to perform the operation again until the desired state is achieved (kinda like built-in retry)

2023-07-18 08:39 UTC, mirii1994 commented on instrumentor/controllers/common.go
> -		backoff := wait.Backoff{
Oh cool, thank you

2023-07-18 08:40 UTC, mirii1994 approved these changes

2023-07-19 09:00 UTC, merged